[package]
name = "dialectic"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.4.11"

[dependencies.rocket_contrib]
version = "0.4.11"
default-features = false
features = ["diesel_mysql_pool", "serve", "json"]
