CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  comment TEXT NOT NULL,
  upvotes INTEGER NOT NULL DEFAULT 0,
  date_posted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)